---
# file: roles/webtier/tasks/main.yml

- name: Install Apache
  yum:
   name: httpd
   state: latest

- name: Copy index.html file
  copy:
    src: /var/www/html/index.html
    dest: /var/www/html/index.html
  notify:
    - Restart Apache

- name: Ensure Apache is running
  service:
    name: httpd
    state: started

- name: Debugging something
  debug:
    msg: "Matched pattern 1"
  when: url is match("/var/www/html/index.html")
