---
- name: Handle A error
  block:
    - name : Create Application Database
      mysql_db:
       name: "{{dbname}}"
       state: present
      register: result

    - name: Create Application DB User
      mysql_user:
        name: "{{dbsuer}}"
        password: "{{upassword}}"
        privs: "*.*:ALL"
        host: '%'
        state: present
  rescue:
    - name: print when errors
      ansible.builtin.debug:
        msg: "I caught an error,Can do stuff here to fix it"
    notify:
      - Install python

